version: '3.9'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
